export const initialValues = {
  PetName: {
    value: '',
    error: '',
    required: true,
    validate: 'text',
    minLength: 2,
    maxLength: 20,
    helperText: 'Custom error message',
  },
  Name: {
    value: '',
    error: '',
    required: true,
    validate: 'text',
    minLength: 2,
    maxLength: 20,
  },
  email: {
    value: '',
    error: '',
    validate: 'email',
  },
  pet_type: {
    value: '',
    error: '',
    validate: 'select',
    required: true,
  },
  breed: {
    value: '',
    error: '',
    validate: 'select',
    required: true,
  },
  date: {
    value: '',
    error: '',
  },
  time: {
    value: '',
    error: '',
  },
  grooming: {
    value: [],
    error: '',
    validate: 'select',
    required: true,
  },
  addon: {
    value: [],
    error: '',
    validate: 'select',
    required: true,
  },
  agreenemt: {
    value: false,
    error: '',
    required: true,
    validate: 'checkbox',
    helperText: 'Please accept our terms and conditions',
  },
  phone: {
    value: '',
    error: '',
    required: true,
    validate: 'phone',
    maxLength: 10,
  },
  idline: {
    value: '',
    error: '',
    required: true,
    validate: 'text',
    helperText: 'Plese input ID LINE',
  },
};
